import type { Config } from 'tailwindcss';
import animate from 'tailwindcss-animate';

export const config: Config = {
  darkMode: 'class',
  content: ['./variables.css'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    fontSize: {
      display: [
        'var(--font-size-display)',
        {
          lineHeight: 'var(--line-height-display)',
          letterSpacing: 'var(--letter-spacing-display)',
        },
      ],
      h1: [
        'var(--font-size-h1)',
        {
          lineHeight: 'var(--line-height-h1)',
          letterSpacing: 'var(--letter-spacing-h1)',
        },
      ],
      h2: [
        'var(--font-size-h2)',
        {
          lineHeight: 'var(--line-height-h2)',
          letterSpacing: 'var(--letter-spacing-h2)',
        },
      ],
      h3: [
        'var(--font-size-h3)',
        {
          lineHeight: 'var(--line-height-h3)',
          letterSpacing: 'var(--letter-spacing-h3)',
        },
      ],
      h4: [
        'var(--font-size-h4)',
        {
          lineHeight: 'var(--line-height-h4)',
          letterSpacing: 'var(--letter-spacing-h4)',
        },
      ],
      h5: [
        'var(--font-size-h5)',
        {
          lineHeight: 'var(--line-height-h5)',
          letterSpacing: 'var(--letter-spacing-h5)',
        },
      ],
      h6: [
        'var(--font-size-h6)',
        {
          lineHeight: 'var(--line-height-h6)',
          letterSpacing: 'var(--letter-spacing-h6)',
        },
      ],
      bodyL: [
        'var(--font-size-body-l)',
        {
          lineHeight: 'var(--line-height-body-l)',
          letterSpacing: 'var(--letter-spacing-body-l)',
        },
      ],
      bodyM: [
        'var(--font-size-body-m)',
        {
          lineHeight: 'var(--line-height-body-m)',
          letterSpacing: 'var(--letter-spacing-body-m)',
        },
      ],
      bodyS: [
        'var(--font-size-body-s)',
        {
          lineHeight: 'var(--line-height-body-s)',
          letterSpacing: 'var(--letter-spacing-body-s)',
        },
      ],
      captionL: [
        'var(--font-size-caption-l)',
        {
          lineHeight: 'var(--line-height-caption-l)',
          letterSpacing: 'var(--letter-spacing-caption-l)',
        },
      ],
      captionM: [
        'var(--font-size-caption-m)',
        {
          lineHeight: 'var(--line-height-caption-m)',
          letterSpacing: 'var(--letter-spacing-caption-m)',
        },
      ],
      captionS: [
        'var(--font-size-caption-s)',
        {
          lineHeight: 'var(--line-height-caption-s)',
          letterSpacing: 'var(--letter-spacing-caption-s)',
        },
      ],
    },
    extend: {
      colors: {
        background: {
          surface: {
            default: 'var(--semantic-neutral-0)',
            inverted: 'var(--semantic-inverted-0)',
            neutral: 'var(--semantic-neutral-1)',
            'neutral-subtle': 'var(--semantic-neutral-2)',
            destructive: 'var(--semantic-negative-1)',
            'destructive-subtle': 'var(--semantic-negative-2)',
            'destructive-accent': 'var(--semantic-negative-8)',
            warning: 'var(--semantic-warning-1)',
            'warning-subtle': 'var(--semantic-warning-2)',
            'warning-accent': 'var(--semantic-warning-8)',
            success: 'var(--semantic-positive-1)',
            'success-subtle': 'var(--semantic-positive-2)',
            'success-accent': 'var(--semantic-positive-8)',
            info: 'var(--semantic-informative-1)',
            'info-subtle': 'var(--semantic-informative-2)',
            'info-accent': 'var(--semantic-informative-8)',
          },
          button: {
            primary: 'var(--semantic-neutral-13)',
            'primary-hover': 'var(--semantic-neutral-12)',
            'primary-disabled': 'var(--semantic-neutral-12)',
            secondary: 'var(--semantic-neutral-10)',
            'secondary-hover': 'var(--semantic-neutral-11)',
            'secondary-disabled': 'var(--semantic-neutral-10)',
            tertiary: 'var(--semantic-neutral-1a)',
            'tertiary-hover': 'var(--semantic-neutral-2a)',
            'tertiary-disabled': 'var(--semantic-neutral-1a)',
            ghost: 'var(--semantic-neutral-0a)',
            'ghost-hover': 'var(--semantic-neutral-1a)',
            'ghost-disabled': 'var(--semantic-neutral-0a)',
            destructive: 'var(--semantic-negative-8)',
            'destructive-hover': 'var(--semantic-negative-9)',
            'destructive-disabled': 'var(--semantic-negative-2)',
            'destructive-secondary': 'var(--semantic-neutral-0)',
            'destructive-secondary-hover': 'var(--semantic-negative-1)',
            'destructive-secondary-disabled': 'var(--semantic-neutral-0)',
            'destructive-tertiary': 'var(--semantic-negative-1a)',
            'destructive-tertiary-hover': 'var(--semantic-negative-2a)',
            'destructive-tertiary-disabled': 'var(--semantic-negative-1a)',
            'destructive-ghost': 'var(--semantic-neutral-0)',
            'destructive-ghost-hover': 'var(--semantic-negative-1a)',
          },
          badge: {
            gray: 'var(--global-gray-2)',
            'gray-accent': 'var(--global-gray-9)',
            blue: 'var(--global-blue-2)',
            'blue-accent': 'var(--global-blue-8)',
            green: 'var(--global-green-2)',
            'green-accent': 'var(--global-green-8)',
            orange: 'var(--global-orange-2)',
            'orange-accent': 'var(--global-orange-8)',
            red: 'var(--global-red-2)',
            'red-accent': 'var(--global-red-8)',
            purple: 'var(--global-purple-2)',
            'purple-accent': 'var(--global-purple-8)',
            white: 'var(--global-base-white)',
            surface: 'var(--semantic-neutral-0)',
          },
          chip: {
            primary: 'var(--semantic-neutral-0)',
            'primary-hover': 'var(--semantic-neutral-1)',
            'primary-active': 'var(--semantic-neutral-0)',
            'primary-disabled': 'var(--semantic-neutral-0)',
            secondary: 'var(--semantic-neutral-1a)',
            'secondary-hover': 'var(--semantic-neutral-2a)',
            'secondary-active': 'var(--semantic-neutral-1a)',
            'secondary-disabled': 'var(--semantic-neutral-1a)',
          },
          accent: {
            gray: 'var(--global-gray-1)',
            'gray-subtle': 'var(--global-gray-2)',
            'gray-accent': 'var(--global-gray-8)',
            blue: 'var(--global-blue-1)',
            'blue-subtle': 'var(--global-blue-2)',
            'blue-accent': 'var(--global-blue-8)',
            green: 'var(--global-green-1)',
            'green-subtle': 'var(--global-green-2)',
            'green-accent': 'var(--global-green-8)',
            orange: 'var(--global-orange-1)',
            'orange-subtle': 'var(--global-orange-2)',
            'orange-accent': 'var(--global-orange-8)',
            red: 'var(--global-red-1)',
            'red-subtle': 'var(--global-red-2)',
            'red-accent': 'var(--global-red-8)',
            purple: 'var(--global-purple-1)',
            'purple-subtle': 'var(--global-purple-2)',
            'purple-accent': 'var(--global-purple-8)',
          },
          checkbox: {
            default: 'var(--semantic-neutral-0)',
            checked: 'var(--semantic-neutral-13)',
            disabled: 'var(--semantic-neutral-03)',
          },
          toggle: {
            default: 'var(--semantic-neutral-5)',
            hover: 'var(--semantic-neutral-6)',
            disabled: 'var(--semantic-neutral-2)',
            active: 'var(--semantic-positive-8)',
            'active-hover': 'var(--semantic-positive-9)',
            'active-disabled': 'var(--semantic-positive-3)',
            handle: 'var(--semantic-neutral-0)',
            'handle-disabled': 'var(--semantic-neutral-4)',
          },
          overlay: {
            normal: 'var(--semantic-neutral-0a)',
            hover: 'var(--semantic-neutral-1a)',
            'active-normal': 'var(--semantic-neutral-1a)',
            'active-hover': 'var(--semantic-neutral-2a)',
            custom: 'var(--semantic-neutral-2a)',
          },
          modal: {
            default: 'var(--semantic-neutral-0)',
            neutral: 'var(--semantic-neutral-1)',
          },
          base: {
            primary: 'var(--semantic-neutral-13)',
            secondary: 'var(--semantic-neutral-9a)',
            tertiary: 'var(--semantic-neutral-7a)',
            quaternary: 'var(--semantic-neutral-5a)',
            inverted: 'var(--semantic-neutral-0)',
            'inverted-secondary': 'var(--inverted-9a)',
            'inverted-tertiary': 'var(--inverted-7a)',
            'inverted-quaternary': 'var(--inverted-6a)',
            'static-dark': 'var(--global-gray-13)',
            'static-dark-secondary': 'var(--global-gray-9a)',
            'static-dark-tertiary': 'var(--global-gray-7a)',
            'static-dark-quaternary': 'var(--global-gray-5a)',
            'static-white': 'var(--global-base-white)',
            'static-white-secondary': 'var(--global-white-9)',
            'static-white-tertiary': 'var(--global-white-7)',
            'static-white-quaternary': 'var(--global-white-5)',
          },
        },
        icon: {
          base: {
            primary: 'var(--semantic-neutral-13)',
            secondary: 'var(--semantic-neutral-9a)',
            tertiary: 'var(--semantic-neutral-7a)',
            quaternary: 'var(--semantic-neutral-5a)',
            inverted: 'var(--semantic-neutral-0)',
            'inverted-secondary': 'var(--inverted-9a)',
            'inverted-tertiary': 'var(--inverted-7a)',
            'inverted-quaternary': 'var(--inverted-6a)',
            'static-dark': 'var(--global-gray-13)',
            'static-dark-secondary': 'var(--global-gray-9a)',
            'static-dark-tertiary': 'var(--global-gray-7a)',
            'static-dark-quaternary': 'var(--global-gray-5a)',
            'static-white': 'var(--global-base-white)',
            'static-white-secondary': 'var(--global-white-9)',
            'static-white-tertiary': 'var(--global-white-7)',
            'static-white-quaternary': 'var(--global-white-5)',
          },
          status: {
            destructive: 'var(--semantic-negative-8)',
            'destructive-secondary': 'var(--semantic-negative-9a)',
            'destructive-tertiary': 'var(--semantic-negative-5a)',
            success: 'var(--semantic-positive-8)',
            'success-secondary': 'var(--semantic-positive-8a)',
            'success-tertiary': 'var(--semantic-positive-5a)',
            warning: 'var(--semantic-warning-8)',
            'warning-secondary': 'var(--semantic-warning-8a)',
            'warning-tertiary': 'var(--semantic-warning-5a)',
            info: 'var(--semantic-informative-8)',
            'info-secondary': 'var(--semantic-informative-8a)',
            'info-tertiary': 'var(--semantic-informative-5a)',
          },
          accent: {
            blue: 'var(--global-blue-11)',
            'blue-inverted': 'var(--global-blue-11)',
            'blue-accent': 'var(--global-blue-8)',
            'blue-secondary': 'var(--global-blue-7a)',
            'blue-tertiary': 'var(--global-blue-5a)',
            green: 'var(--global-green-11)',
            'green-inverted': 'var(--global-green-11)',
            'green-accent': 'var(--global-green-8)',
            'green-secondary': 'var(--global-green-7a)',
            'green-tertiary': 'var(--global-green-5a)',
            orange: 'var(--global-orange-11)',
            'orange-inverted': 'var(--global-orange-11)',
            'orange-accent': 'var(--global-orange-8)',
            'orange-secondary': 'var(--global-orange-7a)',
            'orange-tertiary': 'var(--global-orange-5a)',
            red: 'var(--global-red-11)',
            'red-inverted': 'var(--global-red-11)',
            'red-accent': 'var(--global-red-8)',
            'red-secondary': 'var(--global-red-7a)',
            'red-tertiary': 'var(--global-red-5a)',
            purple: 'var(--global-purple-11)',
            'purple-inverted': 'var(--global-purple-11)',
            'purple-accent': 'var(--global-purple-8)',
            'purple-secondary': 'var(--global-purple-7a)',
            'purple-tertiary': 'var(--global-purple-5a)',
          },
        },
        text: {
          base: {
            primary: 'var(--semantic-neutral-13)',
            secondary: 'var(--semantic-neutral-9a)',
            tertiary: 'var(--semantic-neutral-7a)',
            quaternary: 'var(--semantic-neutral-5a)',
            inverted: 'var(--semantic-neutral-0)',
            'inverted-secondary': 'var(--inverted-9a)',
            'inverted-tertiary': 'var(--inverted-7a)',
            'inverted-quaternary': 'var(--inverted-6a)',
            'static-dark': 'var(--global-gray-13)',
            'static-dark-secondary': 'var(--global-gray-9a)',
            'static-dark-tertiary': 'var(--global-gray-7a)',
            'static-dark-quaternary': 'var(--global-gray-5a)',
            'static-white': 'var(--global-base-white)',
            'static-white-secondary': 'var(--global-white-9)',
            'static-white-tertiary': 'var(--global-white-7)',
            'static-white-quaternary': 'var(--global-white-5)',
          },
          status: {
            destructive: 'var(--semantic-negative-8)',
            'destructive-secondary': 'var(--semantic-negative-9a)',
            'destructive-tertiary': 'var(--semantic-negative-5a)',
            success: 'var(--semantic-positive-8)',
            'success-secondary': 'var(--semantic-positive-8a)',
            'success-tertiary': 'var(--semantic-positive-5a)',
            warning: 'var(--semantic-warning-8)',
            'warning-secondary': 'var(--semantic-warning-8a)',
            'warning-tertiary': 'var(--semantic-warning-5a)',
            info: 'var(--semantic-informative-8)',
            'info-secondary': 'var(--semantic-informative-8a)',
            'info-tertiary': 'var(--semantic-informative-5a)',
          },
          accent: {
            blue: 'var(--global-blue-11)',
            'blue-inverted': 'var(--global-blue-11)',
            'blue-accent': 'var(--global-blue-8)',
            'blue-secondary': 'var(--global-blue-7a)',
            'blue-tertiary': 'var(--global-blue-5a)',
            green: 'var(--global-green-11)',
            'green-inverted': 'var(--global-green-11)',
            'green-accent': 'var(--global-green-8)',
            'green-secondary': 'var(--global-green-7a)',
            'green-tertiary': 'var(--global-green-5a)',
            orange: 'var(--global-orange-11)',
            'orange-inverted': 'var(--global-orange-11)',
            'orange-accent': 'var(--global-orange-8)',
            'orange-secondary': 'var(--global-orange-7a)',
            'orange-tertiary': 'var(--global-orange-5a)',
            red: 'var(--global-red-11)',
            'red-inverted': 'var(--global-red-11)',
            'red-accent': 'var(--global-red-8)',
            'red-secondary': 'var(--global-red-7a)',
            'red-tertiary': 'var(--global-red-5a)',
            purple: 'var(--global-purple-11)',
            'purple-inverted': 'var(--global-purple-11)',
            'purple-accent': 'var(--global-purple-8)',
            'purple-secondary': 'var(--global-purple-7a)',
            'purple-tertiary': 'var(--global-purple-5a)',
          },
        },
        border: {
          base: {
            neutral: 'var(--semantic-neutral-3)',
            'neutral-subtle': 'var(--semantic-neutral-4)',
            info: 'var(--semantic-informative-4)',
            success: 'var(--semantic-positive-4)',
            warning: 'var(--semantic-warning-4)',
            destructive: 'var(--semantic-destructive-4)',
            brand: 'var(--semantic-brand-4)',
            divider: 'var(--semantic-neutral-2)',
            alpha: 'var(--semantic-neutral-2a)',
            'alpha-white': 'var(--global-white-3)',
            surface: 'var(--semantic-neutral-0)',
            'surface-neutral': 'var(--semantic-neutral-1)',
            inverted: 'var(--semantic-inverted-0)',
          },
          select: {
            primary: 'var(--semantic-brand-8)',
            secondary: 'var(--semantic-brand-4)',
            destructive: 'var(--semantic-negative-8)',
            'destructive-secondary': 'var(--semantic-negative-4)',
          },
          accent: {
            blue: 'var(--global-blue-5)',
            'blue-accent': 'var(--global-blue-8)',
            green: 'var(--global-green-5)',
            'green-accent': 'var(--global-green-8)',
            orange: 'var(--global-orange-5)',
            'orange-accent': 'var(--global-orange-8)',
            red: 'var(--global-red-5)',
            'red-accent': 'var(--global-red-8)',
            purple: 'var(--global-purple-5)',
            'purple-accent': 'var(--global-purple-8)',
          },
          action: {
            normal: 'var(--semantic-neutral-3)',
            hover: 'var(--semantic-neutral-4)',
            disabled: 'var(--semantic-neutral-2)',
            focus: 'var(--semantic-brand-8)',
            'focus-light': 'var(--semantic-brand-6)',
            'focus-destructive': 'var(--semantic-negative-8)',
            'focus-destructive-light': 'var(--semantic-negative-6)',
            destructive: 'var(--semantic-negative-4)',
            'destructive-hover': 'var(--semantic-negative-5)',
            'destructive-disabled': 'var(--semantic-negative-3a)',
            success: 'var(--semantic-positive-4)',
            'success-hover': 'var(--semantic-positive-5)',
            warning: 'var(--semantic-warning-4)',
            'warning-hover': 'var(--semantic-warning-5)',
            info: 'var(--semantic-informative-4)',
            'info-hover': 'var(--semantic-informative-5)',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [animate],
};
